# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'BGTasks-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BGTasks-Example
#  pod 'BGTasks', '1.0.6'
#  pod 'BGTasks', :git => 'https://github.com/PhonePe/BGTasks'
  pod 'BGTasks', :path => '../BGTasks.podspec'

  target 'BGTasks-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod "Nimble", '9.2.0'
    pod "Quick", '4.0.0'
  end
  
  target 'BGTasks-UnitTests' do
    inherit! :search_paths
    # Pods for testing
    pod "Nimble", '9.2.0'
    pod "Quick", '4.0.0'
  end

end
